export default {
    basic: {
        series: "Product series refers to the series that the current product belongs to",
        market: "Market positioning refers to the positioning suitable for the current product, not representing the final actual usage"
    },
    cpu: {
        voltage: "Typical voltage refers to the regular operating voltage required for the processor to run stably at its rated frequency.",
        tpc: `Typical Power Consumption (TPC) refers to the average power consumption of the processor under normal operating conditions.

        Note: Typical power consumption does not represent the actual power consumption of the processor.`,
        tdp: `Thermal Design Power (TDP) refers to the maximum heat value generated by the processor under extreme load.

        Note: TDP does not represent the actual power consumption of the processor.`
    },
    memory: {
        ecc: `ECC memory is a system memory that can detect and correct common internal data corruption, used to improve system stability and reliability. For every 64 bits of data stored, an additional 8 bits are used to store error correction codes. When data is read, the system automatically detects single-bit data errors through the error correction codes and immediately corrects them, preventing erroneous data from being used by the processor.
        
        Note: Support for ECC memory is motherboard-dependent; please contact the relevant manufacturer to inquire about compatibility.`
    },
    exp: {
        io_name: "I/O interface is the bus interface for data exchange between the processor and external devices. Includes HyperTransport bus and PCI Express controllers",
        io_rev: `I/O revision is the version supported by the processor's I/O communication interface.
        
        Note: Support for PCI Express 4.0 depends on motherboard and corresponding firmware support; if in doubt, please contact the relevant manufacturer.`,
        d2d: "Die-to-die interconnect refers to the connection technology between chips, encompassing both die-to-die connections and chip-to-chip connections.",
        d2d_name: `Die-to-die interconnect technology refers to the name of the interconnect technology supported by the processor.

        Loongson Coherent Link: A die-to-die interconnect technology independently developed by Loongson, offering lower latency and higher bandwidth compared to HyperTransport 3.0.
        HyperTransport: A high-speed, low-latency, point-to-point serial/parallel bus technology primarily used to connect processors, chipsets, memory controllers, and I/O devices within a computer.`
    },
    package: {
        temperature: "Case temperature range refers to the allowable temperature interval for the processor's outer shell surface.",
        t_case: " (Case Temperature) refers to the maximum allowable temperature on the processor's outer shell surface.\n\nNote:",
        t_junction: "(Junction Temperature) refers to the maximum operating temperature inside the processor chip, at the transistor cell level.\n\nNote:",
        t_notice: "Temperature does not represent the actual temperature during processor operation; it depends on the performance of the cooling solution used."
    },
    power: {
        shutdown_of_the_clocks: "Clock gating is a low-power design technique that temporarily shuts off the clock signal of circuit modules when they are idle, thereby avoiding unnecessary dynamic power consumption.",
        frequency_scaling: "Dynamic frequency scaling is the processor's ability to dynamically adjust its operating frequency based on real-time load and power requirements.",
        voltage_scaling: "Dynamic voltage scaling refers to the processor's ability to dynamically adjust its core operating voltage within a specified range based on current operating frequency and load."
    },
    tech: {
        isa: {
            info: "Instruction set refers to a set of basic commands and instructions that the processor understands and can execute. The displayed value represents the instruction set with which the processor is compatible.",
            extensions: "Instruction set extensions are additional instructions added on top of the base instruction set that can improve performance while ensuring the same operation on multiple data objects.",
            LBT: "Loongson Binary Translation (LBT)\nUsed to improve the execution efficiency of cross-instruction system binary translation on the LoongArch platform. It extends upon the base part and similarly includes both non-privileged and privileged instruction set sections.",
            LVZ: "Loongson Virtualization (LVZ)\nUsed to provide hardware acceleration for operating system virtualization to improve performance. This part primarily involves privileged resources, including some privileged instructions and control status registers, as well as adding new functionality in exceptions, interrupts, memory management, etc.\n\nNote: If the processor does not support this instruction set, hardware-accelerated virtualization cannot be used.",
            LSX: "Loongson SIMD Extension (LSX)\nThis instruction set allows a single instruction to process multiple data simultaneously. It is implemented in the processor's dedicated registers and is used to accelerate compute-intensive tasks. LSX supports a vector width of 128 bits.",
            LASX: "Loongson Advanced SIMD Extension (LASX)\nSimilar to LSX, but LASX supports a vector width of 256 bits."
        }
    }
}